baseurl                  = "https://lowf.at/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Lowfat Industries, LLC"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    #favicon              = "sam.ico"
    favicon              = "img/icon.png"
    homepage             = "home"                           # What to call the home page link
    footerText           = "Lowfat Industries, LLC"

# Metadata for Open Graph and Twitter
    description          = "Connecting human insights with technology for impact."               # Max 160 characters show in search results
    images               = ["img/icon.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Lowfat Industries, LLC"
    # rss                = ""

[[params.mainMenu]]
    link = "https://lowfat.slack.com/"
    text = "chat"

[[params.mainMenu]]
    link = "https://stats.foldingathome.org/team/261811"
    text = "folding@home"

[[params.mainMenu]]
    link = "https://prv.lowf.at/"
    text = "private"

[[params.mainMenu]]
    link = "about"
    text = "about Lowfat Industries, LLC"

[imaging]
    quality = 75
